-- ON PRIMARY NODE

USE [master]
GO

-- REMOVE DATABASES FROM AVAILABILITY GROUP
ALTER AVAILABILITY GROUP [AG_GCSQL0506_01]
REMOVE DATABASE [Bravos];
GO

-- SET DATABASES TO READONLY
ALTER DATABASE [Bravos] SET READ_ONLY WITH NO_WAIT;
GO

-- FULL BACKUP OF DATABASES
EXEC msdb.dbo.sp_start_job @job_name=N'DatabaseBackup - USER_DATABASES - FULL';

-- VERIFY BACKUP SUCCESS
-- DROP USER DATABASES

-- DROP DATABASE [Bravos];

-- STOP SQL SERVICE


