-- ON PRIMARY NODE

USE [master]
GO

-- REMOVE DATABASES FROM AVAILABILITY GROUP
ALTER AVAILABILITY GROUP [AG_GCSQL0506_02]
REMOVE DATABASE [Bravos];
GO
ALTER AVAILABILITY GROUP [AG_GCSQL0506_02]
REMOVE DATABASE [Citadel];
GO
ALTER AVAILABILITY GROUP [AG_GCSQL0506_02]
REMOVE DATABASE [CRSDBA];
GO
ALTER AVAILABILITY GROUP [AG_GCSQL0506_02]
REMOVE DATABASE [Inbound];
GO
ALTER AVAILABILITY GROUP [AG_GCSQL0506_02]
REMOVE DATABASE [IronBank];
GO
ALTER AVAILABILITY GROUP [AG_GCSQL0506_02]
REMOVE DATABASE [KingsLanding];
GO
ALTER AVAILABILITY GROUP [AG_GCSQL0506_02]
REMOVE DATABASE [Qyburn];
GO
ALTER AVAILABILITY GROUP [AG_GCSQL0506_02]
REMOVE DATABASE [Raven];
GO
ALTER AVAILABILITY GROUP [AG_GCSQL0506_02]
REMOVE DATABASE [RiverRun];
GO



-- SET DATABASES TO READONLY
ALTER DATABASE [Bravos] SET READ_ONLY WITH NO_WAIT;
GO

ALTER DATABASE [Citadel] SET READ_ONLY WITH NO_WAIT;
GO

ALTER DATABASE [CRSDBA] SET READ_ONLY WITH NO_WAIT;
GO

ALTER DATABASE [Inbound] SET READ_ONLY WITH NO_WAIT;
GO

ALTER DATABASE [IronBank] SET READ_ONLY WITH NO_WAIT;
GO

ALTER DATABASE [KingsLanding] SET READ_ONLY WITH NO_WAIT;
GO

ALTER DATABASE [Qyburn] SET READ_ONLY WITH NO_WAIT;
GO

ALTER DATABASE [Raven] SET READ_ONLY WITH NO_WAIT;
GO

ALTER DATABASE [RiverRun] SET READ_ONLY WITH NO_WAIT;
GO

-- FULL BACKUP OF DATABASES
EXEC msdb.dbo.sp_start_job @job_name=N'DatabaseBackup - USER_DATABASES - FULL';

-- VERIFY BACKUP SUCCESS
-- DROP USER DATABASES

/*
DROP DATABASE [Bravos];
GO

DROP DATABASE [Citadel];
GO

DROP DATABASE [CRSDBA];
GO

DROP DATABASE [Inbound];
GO

DROP DATABASE [IronBank];
GO

DROP DATABASE [KingsLanding];
GO

DROP DATABASE [Qyburn];
GO

DROP DATABASE [Raven];
GO

DROP DATABASE [RiverRun];
GO

*/

-- STOP SQL SERVICE


