USE [master]
GO

EXECUTE AS LOGIN='sa'

/****** Object:  Database [DBA_Utilities]    Script Date: 7/11/2017 9:31:33 AM ******/
CREATE DATABASE [DBA_Utilities]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBA_Utilities', FILENAME = N'R:\Data\DBA_Utilities.mdf' , SIZE = 65536KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBA_Utilities_log', FILENAME = N'U:\Logs\DBA_Utilities_log.ldf' , SIZE = 65536KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
--ALTER DATABASE [DBA_Utilities] SET COMPATIBILITY_LEVEL = 100
--GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBA_Utilities].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DBA_Utilities] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBA_Utilities] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBA_Utilities] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBA_Utilities] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBA_Utilities] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBA_Utilities] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBA_Utilities] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DBA_Utilities] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBA_Utilities] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBA_Utilities] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBA_Utilities] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBA_Utilities] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBA_Utilities] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBA_Utilities] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBA_Utilities] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBA_Utilities] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBA_Utilities] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBA_Utilities] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBA_Utilities] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBA_Utilities] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBA_Utilities] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBA_Utilities] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBA_Utilities] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBA_Utilities] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBA_Utilities] SET  MULTI_USER 
GO
ALTER DATABASE [DBA_Utilities] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBA_Utilities] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBA_Utilities] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBA_Utilities] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
